name: Build

on:
  workflow_dispatch:
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up jdk
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Fetch and build
        env:
          GHTOKEN: ${{ secrets.GHTOKEN }}
        run: bash build.sh
        shell: bash

      - name: Sign apk # https://github.com/tytydraco/public-keystore
        run: |
          apksigner="$(find $ANDROID_SDK_ROOT/build-tools -name apksigner | sort -r | head -n 1)"
          "$apksigner" sign --ks public.jks --ks-key-alias public --ks-pass pass:public --key-pass pass:public --in ./revanced.apk --out ./revanced_signed.apk
        shell: bash

      - name: Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: revanced-nonroot
          path: ./revanced_signed.apk
      - name: Upload patch log
        uses: actions/upload-artifact@v2
        with:
          name: PatchLog
          path: ./Patch.log

uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Release ${{ env.date_now }}"
          files: |
            build/*.apk
            vanced-microG.apk
